import type { SpecSurface } from "./parse.js";

/** Where the vendored spec came from: `spec/source.json`. */
export interface SpecSource {
  readonly repository: string;
  readonly path: string;
  readonly commit: string;
  readonly ref: string;
  readonly sha256: string;
}

/** Renders `packages/sdk/src/generated/spec.ts`, formatted as Biome formats it. */
export function render(surface: SpecSurface, source: SpecSource): string {
  const out: string[] = [
    "// GENERATED by tools/spec-codegen from spec/SPEC.md — do not edit.",
    `// Source: ${source.repository}/${source.path} at ${source.commit.slice(0, 7)} (${source.ref}).`,
    "// Regenerate with `pnpm spec:generate`; CI runs `pnpm spec:check`.",
    "",
    '/** Where an error arises (SPEC.md §10, "Errors by where they arise"). */',
    'export type ErrorOrigin = "ledger" | "platform" | "binding";',
    "",
    "/** Every live error of SPEC.md §10, in the spec's order. */",
    "export const TICKETTO_ERROR_CODES = [",
    ...surface.errors.flatMap((error) => [doc(error.condition, "  "), `  "${error.id}",`]),
    "] as const;",
    "",
    "/** An error of SPEC.md §10, by its spec identifier. */",
    "export type TickettoErrorCode = (typeof TICKETTO_ERROR_CODES)[number];",
    "",
    "/**",
    " * Where each error arises: `ledger` errors are raised by the ledger's rules and",
    " * are exercised by the conformance suite (`REQ-SDK-7`); `platform` errors are",
    " * raised by Kippu; `binding` errors by a backend binding.",
    " */",
    "export const TICKETTO_ERROR_ORIGINS: { readonly [Code in TickettoErrorCode]: ErrorOrigin } = {",
    ...surface.errors.map((error) => `  "${error.id}": "${error.origin}",`),
    "};",
    "",
    "/** Every live invariant of SPEC.md §9, in the spec's order. */",
    "export const INVARIANT_IDS = [",
    ...surface.invariants.flatMap((invariant) => [
      doc(invariant.text, "  "),
      `  "${invariant.id}",`,
    ]),
    "] as const;",
    "",
    "/** An invariant of SPEC.md §9, by its spec identifier. */",
    "export type InvariantId = (typeof INVARIANT_IDS)[number];",
    "",
  ];
  return out.join("\n");
}

function doc(text: string, indent: string): string {
  return `${indent}/** ${text.replaceAll("*/", "*\\/")} */`;
}
